server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # useUnicode=true&amp&characterEncoding=utf-8
    url: jdbc:mysql://101.37.80.37:3306/smart_iot?useSSL=false&&serverTimezone=GMT%2B8&useLegacyDatetimeCode=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    mongodb:
      uri: mongodb://root:123456@101.37.80.37:27017/smart_iot?authSource=admin

mybatis:
  mapper-locations: classpath:mapper/*

mqtt:
  username: test
  password: test
  url: tcp://101.37.80.37:1883
  sender:
    clientId: sender
    defaultTopic: default
  receiver:
    clientId: receiver
    defaultTopic: default